-- Capability is the tool's primary output type, not its model.
-- No verified model mappings are seeded: verified_model_slug stays null.
insert into ai_tools (slug, name, aliases, capability) values
  ('chatgpt',           'ChatGPT',           '{chat gpt}',                      'text'),
  ('claude',            'Claude',            '{claude ai}',                     'text'),
  ('gemini',            'Gemini',            '{google gemini}',                 'text'),
  ('microsoft-copilot', 'Microsoft Copilot', '{copilot,bing chat}',             'text'),
  ('perplexity',        'Perplexity',        '{}',                              'text'),
  ('jasper',            'Jasper',            '{jasper ai}',                     'text'),
  ('notion-ai',         'Notion AI',         '{notion}',                        'text'),
  ('grammarly',         'Grammarly',         '{}',                              'text'),
  ('copy-ai',           'Copy.ai',           '{copyai}',                        'text'),
  ('writesonic',        'Writesonic',        '{}',                              'text'),
  ('deepseek',          'DeepSeek',          '{}',                              'text'),
  ('le-chat',           'Le Chat',           '{mistral}',                       'text'),
  ('meta-ai',           'Meta AI',           '{}',                              'text'),
  ('github-copilot',    'GitHub Copilot',    '{}',                              'code'),
  ('cursor',            'Cursor',            '{}',                              'code'),
  ('windsurf',          'Windsurf',          '{codeium}',                       'code'),
  ('tabnine',           'Tabnine',           '{}',                              'code'),
  ('midjourney',        'Midjourney',        '{}',                              'image'),
  ('dall-e',            'DALL-E',            '{dalle}',                         'image'),
  ('leonardo',          'Leonardo AI',       '{leonardo}',                      'image'),
  ('ideogram',          'Ideogram',          '{}',                              'image'),
  ('stable-diffusion',  'Stable Diffusion',  '{}',                              'image'),
  ('adobe-firefly',     'Adobe Firefly',     '{firefly}',                       'image'),
  ('higgsfield',        'Higgsfield',        '{higgsfield ai}',                 'video'),
  ('runway',            'Runway',            '{runwayml,runway ml}',            'video'),
  ('sora',              'Sora',              '{}',                              'video'),
  ('pika',              'Pika',              '{pika labs}',                     'video'),
  ('synthesia',         'Synthesia',         '{}',                              'video'),
  ('heygen',            'HeyGen',            '{}',                              'video'),
  ('luma',              'Luma Dream Machine','{luma,dream machine}',            'video'),
  ('kling',             'Kling',             '{kling ai}',                      'video'),
  ('elevenlabs',        'ElevenLabs',        '{eleven labs}',                   'audio'),
  ('suno',              'Suno',              '{}',                              'audio'),
  ('udio',              'Udio',              '{}',                              'audio'),
  ('murf',              'Murf',              '{murf ai}',                       'audio'),
  ('otter',             'Otter',             '{otter ai}',                      'audio')
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  capability = excluded.capability;
